<?php

namespace Custom\Exercise13\Block;

class Index extends \Magento\Framework\View\Element\Template
{
    public function getData($key = '', $index = null)
    {
        return (date('d-m-Y')); // TODO: Change the autogenerated stub
    }
    public function getDate()
    {
        return date('d-m-Y');
    }
}
